### ISSUE TITLE
博主您好，有详细的部署教程吗，部署的前提准备是下载到虚拟环境中吗

### ISSUE THREAD

**Issue by kxuanm** [coolbeevip/langchain-lab#8]
博主您好，有详细的部署教程吗，部署的前提准备是下载到虚拟环境中吗，感谢百忙之中的回复

**Comment by coolbeevip** [comment]
> 博主您好，有详细的部署教程吗，部署的前提准备是下载到虚拟环境中吗，感谢百忙之中的回复

按照首页的快速部署就可以了 https://github.com/coolbeevip/langchain-lab/blob/main/README_ZH.md

**Comment by kxuanm** [comment]
所以部署起来不需要linux和make工具吗，感谢您的回复

**Comment by coolbeevip** [comment]
> 所以部署起来不需要linux和make工具吗，感谢您的回复

刚才看了一下，最近推送 docker 好像都失败了。

如果你要在本地启动可以看开发指南 https://github.com/coolbeevip/langchain-lab/blob/main/README_ZH.md#%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97

这需要一点 makefile 和 python 的知识。如果你是 windows 可以打开 Makefile 文件去执行里面的 python 命令

**Comment by kxuanm** [comment]
好的，非常感谢

**Comment by coolbeevip** [comment]
> 好的，非常感谢

我刚刚修复了镜像 https://hub.docker.com/r/coolbeevip/langchain-lab ，你可以直接使用以下命令启动一个镜像，换成你的 OPENAI_API_BASE 和 OPENAI_API_KEY

```shell
docker run -d --rm -p 8080:8080 \
-e OPENAI_API_BASE=https://api.openai.com/v1 \
-e OPENAI_API_KEY=sk-xxx \
coolbeevip/langchain-lab
```

然后在浏览器上访问 http://localhost:8080 就可以了

<img width="1466" alt="image" src="https://github.com/coolbeevip/langchain-lab/assets/4271525/d45be62c-8312-4053-8b22-8743ee3d8cd2">
